### ISSUE TITLE
Posts not visible

### ISSUE THREAD

**Issue by viaahmed** [Royal-lobster/jntuvnews-reactjs#3]
Great Initiative 👍 @Royal-lobster 
I visited the website https://jntuk-ucev-news.web.app/ but found only an about section.
What could be the reason?

**Comment by Royal-lobster** [comment]
Ohh thanks ! I am porting this site to https://ucevit.vercel.app I think the backend proxy settings are changed for this old site while setting the new one.

**Comment by Royal-lobster** [comment]
Changed the link address to https://jntuvnews.vercel.app it should work as expected !
